name: Check pull request

on: [pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
    - name: Build with dotnet
      run: dotnet build --configuration Release
