name: Push release Docker image

on:
  release:
    types: [released]

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get release tag
        run: |
          tag=`echo ${{ github.ref }} | sed s=refs/tags/v==`
          echo "::set-output name=tag::${tag}"
        id: get-tag
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: SlackLineBridge/Dockerfile
          push: true
          tags: |
            ydkk/slack-line-bridge:latest
            ydkk/slack-line-bridge:${{ steps.get-tag.outputs.tag }}
